### YamlMime:TSType
name: DurableError
uid: durable-functions.DurableError
package: durable-functions
summary: >-
  A specfic error thrown when a scheduled activity or suborchestrator has
  failed.

  This error can be checked for via `instanceof` guards to catch only exceptions
  thrown

  by the DurableJS library.
fullName: DurableError
type: class
constructors:
  - name: DurableError(string | undefined)
    uid: durable-functions.DurableError.constructor
    package: durable-functions
    summary: ''
    syntax:
      content: 'new DurableError(message: string | undefined)'
      parameters:
        - id: message
          type: string | undefined
          description: ''
properties:
  - name: Error
    uid: durable-functions.DurableError.Error
    package: durable-functions
    summary: ''
    fullName: Error
    syntax:
      content: 'static Error: ErrorConstructor'
      return:
        type: ErrorConstructor
        description: ''
  - name: message
    uid: durable-functions.DurableError.message
    package: durable-functions
    summary: ''
    fullName: message
    syntax:
      content: 'message: string'
      return:
        type: string
        description: ''
  - name: name
    uid: durable-functions.DurableError.name
    package: durable-functions
    summary: ''
    fullName: name
    syntax:
      content: 'name: string'
      return:
        type: string
        description: ''
  - name: stack
    uid: durable-functions.DurableError.stack
    package: durable-functions
    summary: ''
    fullName: stack
    syntax:
      content: 'stack?: string'
      return:
        type: string
        description: ''
extends: Error
